### ISSUE TITLE
Optimize Token VBL Generation

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#1218]
**Is your feature request related to a problem? Please describe.**
Token VBL generation produces very complex VBL structures leading to poor performance.  Especially when used on map images.

**Describe the solution you'd like**
Use the polygon simplification of the JTS libs to reduce the number of points and edges produced by the VBL generation.

**TODO:**
- [x] ALL the UI, but must first determine what UI is needed
- [x] Create Issue
- [x] Take work off the UI thread?
- [x] Going to need some wiki docs

**Additional context**
[JTS Lib Simplify](https://locationtech.github.io/jts/javadoc/org/locationtech/jts/simplify/package-summary.html)

Campaign file with two maps and closed/open object images.
[VBL Simplified Test-cmpgn.zip](https://github.com/RPTools/maptool/files/4142897/VBL.Simplified.Test-cmpgn.zip)

**Comment by Phergus** [comment]
D-P simplify cannot handle images with holes but does a great job on images that are otherwise solid.

**MT 1.5.12**
![Token VBL 1 5 12](https://user-images.githubusercontent.com/34379254/73596240-d75ed900-44dd-11ea-8ab7-1c749daffbaf.png)

**MT 1.6 develop**
![Token VBL 1 6 dev](https://user-images.githubusercontent.com/34379254/73596245-e47bc800-44dd-11ea-907b-8e85f7bd47aa.png)

See campaign attached to top for closed form images.

**Comment by Phergus** [comment]
Need to test with the other simplify methods.

**Comment by JamzTheMan** [comment]
I think I one of the methods had a second option that may need to be explored.

I assume we want holes for things like caverns and such.

I'm liking the reduction in points though!

**Comment by Phergus** [comment]
Need to look at the options and see if they can help.

**Comment by JamzTheMan** [comment]
Lots of options added to the VBL panel 😨 
Most are temporary until we find the best JTS method (I don't think we need to supply an option here, and will always optimize I think is best)

Color picking isn't enabled yet but I see that replacing "Sensitivity" (the old Alpha Sensitivity" and let you pick a RGBA instead. So you could pick "black" vs just alpha.

Added an Inverse button so you can generate VBL around an object vs over now, good for maps!

FWIW the Image -> Area is the longest (10+ seconds for maps) but the Optimization is in milliseconds usually so I started to cache the Image -> Area work and it's only redone if you change sensitivity or click the generate button.  There is still some bugs on opening up the dialog and keeping state for that so, ya. More to do...

![image](https://user-images.githubusercontent.com/8051654/75088552-780c4b80-5514-11ea-8364-2403bee29423.png)

**Comment by JamzTheMan** [comment]
Oh, and I added point counts to the preview for debugging but thinking of leaving it in permanently, or at least the optimized number)

AND also added zooming/panning to the preview window! Gotta see those pixels!

Here are some maps I used for testing. It Seems to handle holes ok in all JTS optimizations...
![image](https://user-images.githubusercontent.com/8051654/75088644-b6eed100-5515-11ea-8138-4e0a3361f3cf.png)

**Comment by Phergus** [comment]
Try these:
![Square Hollow](https://user-images.githubusercontent.com/34379254/75094454-82483d00-5548-11ea-9e10-adadd3f87d5a.png)

![MapTool VBL Demo 01 VBL Mask bigger](https://user-images.githubusercontent.com/34379254/75094463-92f8b300-5548-11ea-9c5a-ee9158540011.png)

**Comment by JamzTheMan** [comment]
Now using .setEnsureValid(false) and not forcing valid "geometry" any more seems to fix the issue.

May need to test a few more odd shapes here and there...

**Comment by JamzTheMan** [comment]
Optimized the image translation to Area, by slicing the image up I got over 32x performance increase on this map!

*Note I was going to multi-thread it into slices but even before that, just by slicing the image into 100x100 chunks, the  Area.add math is a lot less intensive, The following image use to take 32 seconds and now averages < 1 second.

I may still throw this into a thread pool and see if we can do this in 100-200 ms instead for even better UX (right now this is still on the UI thread...)

![Cave1---Transparent](https://user-images.githubusercontent.com/8051654/75119501-f66a0a00-5648-11ea-8168-6f35b8d9cd73.png)

**Comment by JamzTheMan** [comment]
OK, I believe I'm all done with this issue, barring any bugs/suggestions.

Here is a macro for fun and documented usage:

```
[h: sensitivity = 10]
[h: inverse = 0]

<!-- Black -->
[h: red   = 0]
[h: green = 0]
[h: blue  = 0]
[h: alpha = 255]

[h: level = 2]
[h: method = "Douglas Peucker"]
[h: method2 = "Topology Preserving"]
[h: method2 = "VW Simplifier"]
[h: method2 = "No Optimization"]

<!-- Options with color -->
[h: options = json.set("{}", "shape", "auto", "inverse", inverse, "r", red, "g", green, "b", blue, "a", alpha)]

<!-- Options with default color of transparent -->
[h: options = json.set("{}", "shape", "auto", "sensitivity", sensitivity, "inverse", inverse, "level", level, "method", method)]

[h: startTime = json.get(getInfo("Client"), "timeInMs")]
[h: pointCount = setTokenVBL(options)]
[h: endTime = json.get(getInfo("Client"), "timeInMs")]

[h: timeToComplete = endTime - startTime]

Results using <i>{method}</i>: {pointCount} points, and took {timeToComplete}ms
```

**Comment by Phergus** [comment]
[Intro to Tokens - VBL page updated](http://www.lmwcs.com/rptools/wiki/Introduction_to_Tokens#VBL)
[setTokenVBL page updated](http://www.lmwcs.com/rptools/wiki/setTokenVBL)

**Comment by Phergus** [comment]
Tested and working as expected.  Closing.

**Comment by Merudo** [comment]
There is a small bug in a token editor: after the VBL color has been picked once, the cursor no longer changes to the crosshair cursor. PR #1544 fixes this.
