### ISSUE TITLE
[Refeactoring]: Campaign Properties Dialog

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#4634]
```[tasklist]
### Tasks
- [x] Label alignment
- [x] Tooltips for import buttons and combo box
- [x] Remove trailing colons
- [x] Grammar and spelling
```
