### ISSUE TITLE
[Feature]: Improved and enhanced token layout options

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#5096]
### Describe the Problem

I'm mostly frustrated when there was already an issue I said I would have a go at addressing and can never find it again.

Token layout is a tiny panel in a cramped tab of the edit token dialog. It is imprecise and almost impossible to use on anything of size greater then 1 map grid size. It also lacks access to control over the independant scaling of a token image in the horizontal and vertical axes as well as rotation of the token issue.

The dialog also fails to contain all the available UI at larger text sizes, often putting the Ok/Cancel buttons off screen.

### The Solution you'd like

A bigger, more accessible, more sophisticated, and easier to use GUI

### Alternatives that you've considered.

None

### Additional Context

Also ties-in to #997, #1447, #3424,  #4886 , #4934, and no doubt a bunch of others
```[tasklist]
### Tasks
- [ ] https://github.com/RPTools/maptool/issues/5101
- [x] https://github.com/RPTools/maptool/issues/5103
- [ ] https://github.com/RPTools/maptool/issues/5097
- [x] Split token painting out of ZoneRenderer into new support class TokenRenderer
```
